-- =============================================================================
-- Vaccination Data Analysis and Visualization -- Phase 1 SQL Schema
-- Engine: SQLite (portable standard SQL; documented in SQL_SCHEMA.md)
-- Generated by scripts/06_create_schema.py -- do not hand-edit the database;
-- edit this file and rerun the ETL.
-- =============================================================================

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- DIMENSIONS
-- ---------------------------------------------------------------------------

CREATE TABLE dim_country (
    country_code            TEXT PRIMARY KEY,      -- ISO-3166-1 alpha-3 (source: CODE/ISO_3_CODE)
    country_name            TEXT,
    who_region               TEXT,                  -- derived lookup; NULL if undeterminable from source
    who_region_source_intro  TEXT,
    who_region_source_schedule TEXT,
    who_region_conflict      INTEGER,                -- 1 if intro/schedule disagreed (none found in Phase 1 run)
    in_coverage              INTEGER NOT NULL,
    in_incidence             INTEGER NOT NULL,
    in_cases                 INTEGER NOT NULL,
    in_introduction          INTEGER NOT NULL,
    in_schedule               INTEGER NOT NULL
);

CREATE TABLE dim_antigen (
    antigen_code            TEXT PRIMARY KEY,      -- source: coverage.ANTIGEN
    antigen_description     TEXT
);

CREATE TABLE dim_disease (
    disease_code             TEXT PRIMARY KEY,      -- source: incidence/cases.DISEASE
    disease_description      TEXT
);

CREATE TABLE dim_vaccine_schedule_code (
    vaccine_code              TEXT PRIMARY KEY,      -- source: schedule.VACCINECODE
    vaccine_description        TEXT
);

CREATE TABLE dim_aggregate_entity (
    group_type                TEXT NOT NULL,          -- e.g. WHO_REGIONS, GLOBAL, WB_LONG, ...
    entity_code                TEXT NOT NULL,          -- source CODE value for aggregate rows
    entity_name                 TEXT,
    source_table                TEXT,
    PRIMARY KEY (group_type, entity_code)
);

CREATE TABLE dim_vaccine_concept (
    -- Added in Phase 1 final QA. Promotes the vaccine "concept" label used to bridge
    -- coverage/schedule/introduction vocabularies from a bare repeated text value into a
    -- proper dimension with a real primary key, so xwalk_vaccine_family.vaccine_concept can
    -- be an ENFORCED foreign key rather than an implicit, unvalidated text self-join.
    vaccine_concept            TEXT PRIMARY KEY,      -- e.g. 'Polio (IPV/OPV)', 'Measles-Mumps-Rubella'
    keyword_patterns            TEXT                   -- the regex keyword(s) used to derive this concept (for auditability)
);

-- ---------------------------------------------------------------------------
-- CROSSWALKS (ANALYST-DERIVED METADATA -- NOT SOURCE FACT. See DATA_DICTIONARY.md)
-- ---------------------------------------------------------------------------

CREATE TABLE xwalk_antigen_disease (
    antigen_code               TEXT NOT NULL,
    disease_code                TEXT,                  -- NULL when mapping_status = 'unmapped'
    mapping_status               TEXT NOT NULL CHECK (mapping_status IN ('mapped','unmapped')),
    confidence                    TEXT,
    rationale                     TEXT,
    notes                         TEXT,
    -- One antigen may legitimately map to multiple diseases (e.g. DTP -> diphtheria + tetanus +
    -- pertussis), so antigen_code alone must NOT be unique. The composite pair is the correct
    -- natural key: an antigen cannot be linked to the same disease twice. (Multiple unmapped
    -- rows with disease_code=NULL for different antigens are unaffected - each antigen appears
    -- at most once as 'unmapped', enforced separately by application-level validation since
    -- SQL UNIQUE treats NULLs as distinct.)
    UNIQUE (antigen_code, disease_code),
    FOREIGN KEY (antigen_code) REFERENCES dim_antigen(antigen_code),
    FOREIGN KEY (disease_code) REFERENCES dim_disease(disease_code)
);

CREATE TABLE xwalk_vaccine_family (
    vaccine_family_xwalk_id       INTEGER PRIMARY KEY,
    source_table                   TEXT NOT NULL CHECK (source_table IN ('coverage_antigen','schedule_vaccinecode','introduction_description')),
    source_code                    TEXT NOT NULL,
    source_description             TEXT,
    vaccine_concept                 TEXT,               -- NULL when mapping_status = 'unmapped'; FK below
    mapping_status                   TEXT NOT NULL CHECK (mapping_status IN ('mapped','combination_component','unmapped')),
    confidence                        TEXT,
    rationale                         TEXT,
    notes                              TEXT,
    FOREIGN KEY (vaccine_concept) REFERENCES dim_vaccine_concept(vaccine_concept)
);

-- ---------------------------------------------------------------------------
-- COUNTRY-LEVEL FACT TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE fact_coverage (
    coverage_id                  INTEGER PRIMARY KEY,
    country_code                  TEXT NOT NULL,
    year                            INTEGER NOT NULL,
    antigen_code                   TEXT NOT NULL,
    coverage_category               TEXT NOT NULL,
    coverage_category_description    TEXT,
    target_number                    REAL,             -- NULL preserved (80.2% null in source; never fabricated)
    doses_raw                        REAL,             -- original value, incl. negative sentinels, untouched
    doses_clean                       REAL,             -- NULL where doses_raw is -3333 sentinel or implausible negative
    doses_quality_flag                 TEXT NOT NULL,     -- missing / normal / sentinel_not_reported / implausible_negative
    coverage_raw                       REAL,             -- original % value, unclipped (may exceed 100)
    coverage_quality_flag               TEXT NOT NULL,     -- missing / normal / above_100_moderate / extreme_outlier
    coverage_analytical_exclude          INTEGER NOT NULL,   -- 1 only for coverage_quality_flag = extreme_outlier
    UNIQUE (country_code, year, antigen_code, coverage_category),
    FOREIGN KEY (country_code) REFERENCES dim_country(country_code),
    FOREIGN KEY (antigen_code) REFERENCES dim_antigen(antigen_code)
);
CREATE INDEX idx_fact_coverage_country_year ON fact_coverage(country_code, year);
CREATE INDEX idx_fact_coverage_antigen ON fact_coverage(antigen_code);

CREATE TABLE fact_incidence (
    incidence_id                  INTEGER PRIMARY KEY,
    country_code                    TEXT NOT NULL,
    year                              INTEGER NOT NULL,
    disease_code                      TEXT NOT NULL,
    denominator_raw                    TEXT,
    denominator_standardized             TEXT,
    incidence_rate                        REAL,          -- NULL preserved (27.5% null in source)
    UNIQUE (country_code, year, disease_code),
    FOREIGN KEY (country_code) REFERENCES dim_country(country_code),
    FOREIGN KEY (disease_code) REFERENCES dim_disease(disease_code)
);
CREATE INDEX idx_fact_incidence_country_year ON fact_incidence(country_code, year);

CREATE TABLE fact_cases (
    cases_id                       INTEGER PRIMARY KEY,
    country_code                     TEXT NOT NULL,
    year                               INTEGER NOT NULL,
    disease_code                       TEXT NOT NULL,
    cases                                REAL,          -- NULL preserved (22.9% null in source)
    UNIQUE (country_code, year, disease_code),
    FOREIGN KEY (country_code) REFERENCES dim_country(country_code),
    FOREIGN KEY (disease_code) REFERENCES dim_disease(disease_code)
);
CREATE INDEX idx_fact_cases_country_year ON fact_cases(country_code, year);

CREATE TABLE fact_vaccine_introduction (
    introduction_id                 INTEGER PRIMARY KEY,
    country_code                      TEXT NOT NULL,
    year                                INTEGER NOT NULL,
    vaccine_description                 TEXT NOT NULL,
    intro_status                          TEXT,
    who_region_raw                          TEXT,        -- as-sourced, for traceability alongside dim_country.who_region
    UNIQUE (country_code, year, vaccine_description),
    FOREIGN KEY (country_code) REFERENCES dim_country(country_code)
);
CREATE INDEX idx_fact_intro_country_year ON fact_vaccine_introduction(country_code, year);

CREATE TABLE fact_vaccine_schedule (
    schedule_id                      INTEGER PRIMARY KEY,
    country_code                       TEXT NOT NULL,
    year                                 INTEGER NOT NULL,
    vaccine_code                          TEXT NOT NULL,
    schedule_rounds                        INTEGER NOT NULL,
    target_pop                              TEXT,        -- 52.9% null in source, preserved
    target_pop_description                    TEXT,
    geoarea                                    TEXT,
    age_administered                             TEXT,
    source_comment                                 TEXT,
    who_region_raw                                   TEXT,
    UNIQUE (country_code, year, vaccine_code, schedule_rounds, target_pop),
    FOREIGN KEY (country_code) REFERENCES dim_country(country_code),
    FOREIGN KEY (vaccine_code) REFERENCES dim_vaccine_schedule_code(vaccine_code)
);
CREATE INDEX idx_fact_schedule_country_year ON fact_vaccine_schedule(country_code, year);

-- ---------------------------------------------------------------------------
-- AGGREGATE-LEVEL FACT TABLES (regional / income-group / global rollups --
-- NEVER to be joined into country-level analysis by default)
-- ---------------------------------------------------------------------------

CREATE TABLE fact_coverage_aggregate (
    coverage_agg_id                 INTEGER PRIMARY KEY,
    group_type                        TEXT NOT NULL,
    entity_code                         TEXT NOT NULL,
    year                                  INTEGER NOT NULL,
    antigen_code                          TEXT NOT NULL,
    coverage_category                       TEXT NOT NULL,
    target_number                            REAL,
    doses_raw                                 REAL,
    doses_clean                                REAL,
    doses_quality_flag                          TEXT NOT NULL,
    coverage_raw                                 REAL,
    coverage_quality_flag                         TEXT NOT NULL,
    coverage_analytical_exclude                    INTEGER NOT NULL,
    UNIQUE (group_type, entity_code, year, antigen_code, coverage_category),
    FOREIGN KEY (group_type, entity_code) REFERENCES dim_aggregate_entity(group_type, entity_code),
    FOREIGN KEY (antigen_code) REFERENCES dim_antigen(antigen_code)
);

CREATE TABLE fact_incidence_aggregate (
    incidence_agg_id                 INTEGER PRIMARY KEY,
    group_type                         TEXT NOT NULL,
    entity_code                          TEXT NOT NULL,
    year                                   INTEGER NOT NULL,
    disease_code                           TEXT NOT NULL,
    denominator_raw                         TEXT,
    denominator_standardized                  TEXT,
    incidence_rate                             REAL,
    UNIQUE (group_type, entity_code, year, disease_code),
    FOREIGN KEY (group_type, entity_code) REFERENCES dim_aggregate_entity(group_type, entity_code),
    FOREIGN KEY (disease_code) REFERENCES dim_disease(disease_code)
);

CREATE TABLE fact_cases_aggregate (
    cases_agg_id                      INTEGER PRIMARY KEY,
    group_type                          TEXT NOT NULL,
    entity_code                           TEXT NOT NULL,
    year                                    INTEGER NOT NULL,
    disease_code                             TEXT NOT NULL,
    cases                                     REAL,
    UNIQUE (group_type, entity_code, year, disease_code),
    FOREIGN KEY (group_type, entity_code) REFERENCES dim_aggregate_entity(group_type, entity_code),
    FOREIGN KEY (disease_code) REFERENCES dim_disease(disease_code)
);
